-- =============================================================================
-- SaaS Phase 4.3 — PostgreSQL Row Level Security (v40.7 – v40.9)
-- Branch: feature/saas-multitenancy
-- Date: 2026-08-03
--
-- DESIGN
-- • Enables RLS on all 62 tenant-scoped tables (60 from v38/v39 + vendors +
--   marketing_campaigns from v40.5/v40.6).
-- • Policy: PERMISSIVE — allows ALL rows when app.current_tenant is NOT set
--   (empty/null → backward-compat for migrations, crons, existing pool.query calls).
--   When app.current_tenant IS set, only rows whose tenant_id matches are visible.
-- • Application layer already enforces tenant_id in WHERE clauses (Phase 3).
--   RLS is an additional DB-layer safety net — not the primary enforcement layer.
-- • To activate RLS filtering for a query, callers must use withTenantConnection()
--   from lib/tenantRls.ts which wraps the query in a transaction with SET LOCAL.
-- • BYPASSRLS is NOT needed — the permissive "empty = allow all" policy handles
--   the case where the session variable is not set.
-- • Idempotent: safe to re-run (DROP POLICY IF EXISTS + CREATE POLICY).
--
-- ROLLBACK: see saas-phase4-rollback.sql (generated by this script)
-- =============================================================================

BEGIN;

-- ── v40.7: Enable RLS + create tenant_isolation policy on all 62 tables ───────
DO $$
DECLARE
  tbl  TEXT;
  tables TEXT[] := ARRAY[
    -- Core (v38/v39)
    'users','bookings','packages','hajj_groups','pilgrims','branches','agents','staff',
    -- Financial
    'payment_transactions','invoices','receipts','refunds','offline_payments','expenses',
    'journal_entries','journal_entry_lines','payment_schedules','payment_links',
    -- Documents / CRM
    'agreements','agreement_audit_logs','documents','support_tickets','support_messages',
    'feedback','inquiries',
    -- Audit
    'audit_logs','booking_audit_logs','payment_audit_logs','finance_audit_logs',
    -- Leads
    'leads','lead_followups','lead_activities','lead_audit_log','lead_auto_followup_log',
    'lead_assignment_rules','lead_web_forms','lead_web_form_submissions',
    -- Notifications / Comms
    'notification_logs','notification_templates','notification_settings',
    'notification_campaigns','push_campaigns','broadcasts',
    'communication_event_mappings','communication_audit_logs','communication_consents',
    'rcs_template_mappings',
    -- AI / Automation
    'ai_conversations','ai_conversation_messages','ai_knowledge_base',
    'ai_automation_logs','ai_automation_jobs','ai_automation_schedules','ai_automation_webhooks',
    'automation_service_tokens','automation_audit_logs',
    -- Misc
    'otps','api_settings','provider_health_status','crm_assignment_rules',
    -- v40 additions
    'vendors','marketing_campaigns'
  ];
BEGIN
  FOREACH tbl IN ARRAY tables LOOP
    -- Skip if table does not exist
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.tables
       WHERE table_schema = 'public' AND table_name = tbl
    ) THEN
      RAISE NOTICE 'v40.7 SKIP RLS: table % does not exist', tbl;
      CONTINUE;
    END IF;

    -- Skip if tenant_id column does not exist on this table
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
       WHERE table_schema = 'public' AND table_name = tbl AND column_name = 'tenant_id'
    ) THEN
      RAISE NOTICE 'v40.7 SKIP RLS: %.tenant_id column not found', tbl;
      CONTINUE;
    END IF;

    -- Enable RLS (idempotent)
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', tbl);

    -- Drop and recreate policy (idempotent)
    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', tbl);

    -- PERMISSIVE policy:
    --   • COALESCE(..., '') = '' → session var not set → allow all rows (backward compat)
    --   • tenant_id::text = ... → session var IS set → only matching rows
    EXECUTE format($policy$
      CREATE POLICY tenant_isolation ON %I
        AS PERMISSIVE FOR ALL
        TO PUBLIC
        USING (
          COALESCE(current_setting('app.current_tenant', true), '') = ''
          OR tenant_id::text = COALESCE(current_setting('app.current_tenant', true), '')
        )
        WITH CHECK (
          COALESCE(current_setting('app.current_tenant', true), '') = ''
          OR tenant_id::text = COALESCE(current_setting('app.current_tenant', true), '')
        )
    $policy$, tbl);

    RAISE NOTICE 'v40.7 RLS ENABLED: % → policy tenant_isolation created', tbl;
  END LOOP;
  RAISE NOTICE 'v40.7 COMPLETE: RLS enabled on % tables', array_length(tables, 1);
END $$;

-- ── v40.8: Verification — confirm RLS is active on core tables ────────────────
DO $$
DECLARE
  tbl  TEXT;
  rls_enabled BOOLEAN;
  issues INT := 0;
  core TEXT[] := ARRAY[
    'users','bookings','packages','leads','notification_logs',
    'payment_transactions','invoices','agreements'
  ];
BEGIN
  FOREACH tbl IN ARRAY core LOOP
    SELECT relrowsecurity INTO rls_enabled
      FROM pg_class
     WHERE relname = tbl AND relnamespace = 'public'::regnamespace;

    IF rls_enabled IS NULL THEN
      RAISE WARNING 'v40.8 VERIFY: table % not found in pg_class', tbl;
      issues := issues + 1;
    ELSIF NOT rls_enabled THEN
      RAISE WARNING 'v40.8 VERIFY: RLS not enabled on %', tbl;
      issues := issues + 1;
    END IF;
  END LOOP;

  IF issues > 0 THEN
    RAISE EXCEPTION 'v40.8 VERIFY FAILED: % core tables do not have RLS enabled', issues;
  END IF;
  RAISE NOTICE 'v40.8 VERIFICATION PASSED: RLS active on all core tables ✓';
END $$;

-- ── v40.9: Policy count check — ensure policies exist ────────────────────────
DO $$
DECLARE
  policy_count INT;
BEGIN
  SELECT COUNT(*) INTO policy_count
    FROM pg_policies
   WHERE policyname = 'tenant_isolation';

  RAISE NOTICE 'v40.9: tenant_isolation policies active: %', policy_count;

  IF policy_count < 10 THEN
    RAISE WARNING 'v40.9: fewer than 10 tenant_isolation policies found (expected ~62)';
  END IF;
END $$;

COMMIT;
